const ACTIVITIES = [
	"making breakfast.",
	"exercising.",
	"watching a movie.",
	"reading a book.",
	"relaxing on the couch.",
	"taking a walk.",
	"going for a run.",
	"going to the gym.",
	"attending a meeting.",
	"exploring a new city.",
	"cooking a meal.",
	"gardening.",
	"attending a class.",
	"going to a concert.",
	"going to a museum.",
	"visiting a zoo.",
	"going to a theme park.",
	"taking a road trip.",
	"going on a hike.",
	"going to the beach.",
	"going on a vacation.",
	"traveling abroad.",
	"going to a festival.",
	"attending a workshop.",
	"visiting a winery.",
	"attending a book club.",
	"going to a theater.",
	"going to a coffee shop.",
];

export default ACTIVITIES;
